### ISSUE TITLE
ICP calls for "closest" mex function, in conflict with empty "closest.m" file

### ISSUE THREAD

**Issue by Maltergate** [petercorke/machinevision-toolbox-matlab#17]
Hi,

When using the ICP function, a call is made to the closest function (which is a .mex file). However, I suppose for printing help purposes, there's the closest.m file with only comments. In Matlab R2018b, however, this file makes Matlab throw an error as it can be seen:

```
T = icp(SAT, sat_hat)
Attempt to execute SCRIPT closest as a function:
/Users/Maltergate/Library/Application Support/MathWorks/MATLAB Add-Ons/Toolboxes/Machine Vision
Toolbox for MATLAB/vision/closest.m

Error in icp (line 107)
        [corresp,distance] = closest(D, Mk);
```

I am using Matlab R2018b, on Mac (Catalina) and I use the toolbox version 4.2.1.

**Comment by Varun-GP** [comment]
Execute:
>> which -all closest

Verify that the file you expect to execute is being used instead of any other file with the same name. If it is not, rename or delete the files higher on the MATLAB path than the file you expect to use.

Renaming closest.m or keeping only closest.mexw64 works.

**Comment by petercorke** [comment]
MATLAB will always execute the mex file if it's in your path, in preference to the .m file.

Run 

>> which closest 

To see what's going on

**Comment by JorgeLuisMadrid** [comment]
Did you solve the problem?

**Comment by Maltergate** [comment]
No I didn't in the end, I moved to something else. Ticket can be closed.

Thomas Barbier

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
