### ISSUE TITLE
can't use SE3

### ISSUE THREAD

**Issue by csufangyu** [petercorke/machinevision-toolbox-matlab#9]
thanks for your work,I am reading your book,and practice ,and I fellow your code in book,but I meet a error.When I use the  function --CentralCamera in chap15,it told me error to use SE3.>> cam = CentralCamera('default');
Wrong use of SE3
The specified 'SO3' superclass contains a parse error, can not be found in MATLAB's search path, or is hidden by another file with the same name.
error Camera/set.T (line 717)
            c.T = SE3(Tc);
error Camera (line 138)
            c.T = eye(4,4);
error CentralCamera (line 169)
            c = c@Camera(varargin{:}); 

could you help me solve this problem?thanks very much!

**Comment by Abduoit** [comment]
I also faced this issue before and many similar issues, I solved as follow 

1- make sure that you are using right combination with Matlab R2016b or more recent 
If you are reading the first edition of the book then you need to be using RTB9 and MVTB3
If you are reading the second edition of the book then you need to be using RTB10 and MVTB4

2- Make sure the right path is added, 
I usually run this `10.2Robotics Toolbox for MATLAB.mltbx` from matlab and in my case, I see robotics toolbox is added after that in this path `C:\Users\100639008\Documents\MATLAB\Add-Ons\Toolboxes`

3- for MVTB, I select right click and add to the path folders and sub-folders. 

hope this helps

**Comment by NealRainYang** [comment]
I have the same problem .And in the Diagnostic Viewer ,error notice is that:

`----- creating workspace variables: camera, quad, P, pstar
Error evaluating 'InitFcn' callback of block_diagram 'sl_quadrotor_vs'.
Caused by:
The 'SO3' class contains parsing errors, can not be found in MATLAB's search path, or it can be hidden by other files with the same name.`

**Comment by NealRainYang** [comment]
@Abduoit 

I what to know where to get the MVTB3. Looking forward to your reply, Best regards.

**Comment by Abduoit** [comment]
every thing u could find in this website [peter corke](http://petercorke.com/wordpress/toolboxes/machine-vision-toolbox)
